"""create technology categories and technologies

Revision ID: 81009144fc51
Revises: edcb43771235
Create Date: 2026-08-31 16:11:16.210377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81009144fc51'
down_revision: Union[str, Sequence[str], None] = 'edcb43771235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_categories_description'), 'technology_categories', ['description'], unique=True)
    op.create_index(op.f('ix_technology_categories_name'), 'technology_categories', ['name'], unique=True)
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['technology_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_name'), 'technologies', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technologies_name'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_technology_categories_name'), table_name='technology_categories')
    op.drop_index(op.f('ix_technology_categories_description'), table_name='technology_categories')
    op.drop_table('technology_categories')
    # ### end Alembic commands ###
