"""prevent duplicate user skills

Revision ID: edcb43771235
Revises: 6c3dc2bc6230
Create Date: 2026-08-31 15:25:44.477105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edcb43771235'
down_revision: Union[str, Sequence[str], None] = '6c3dc2bc6230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_skill', 'user_skills', ['user_id', 'skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_skill', 'user_skills', type_='unique')
    # ### end Alembic commands ###
